spring:
  application:
    name: Config-Dev

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    prefer-ip-address: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
