server:
  port: 8085

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: "https://github.com/ajaykathwate/Hotel-Rating-System-using-Microservices-"
          clone-on-startup: true

